name: CI/CD Pipeline

on:
  push:
    branches:
      - main    # Trigger เมื่อมีการ Push เข้า Branch 'main'
  pull_request:
    branches:
      - main    # Trigger เมื่อมี Pull Request เข้า Branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # ดึงโค้ดจาก GitHub Repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'       # ใช้ Node.js เวอร์ชัน 16

      - name: Install dependencies
        run: npm install           # ติดตั้ง Dependencies

      - name: Run tests
        run: npm test              # รันคำสั่งเทส
